### ISSUE TITLE
Croatian: FileNotFoundError: [Errno 2] No such file or directory: '/home/user/app/models/tts/tts_models--hrv--fairseq--vits/config.json'

### ISSUE THREAD

**Issue by ak-42** [DrewThomasson/ebook2audiobook#124]
Hi. Running via docker on Ubuntu, using the CPU command from readme.

When I provide the .epub input via the WebUI and select Croatian as language, I get the following crash:

```
ebook2audiobookxtts-1  | Output saved to   /home/user/app/tmp/ebook-b739443d-8954-4008-bee3-072a31172083/croatian.epub
ebook2audiobookxtts-1  | Loading TTS tts_models/hrv/fairseq/vits model from tts_models/hrv/fairseq/vits...
ebook2audiobookxtts-1  | Traceback (most recent call last):
ebook2audiobookxtts-1  |   File "/home/user/app/lib/functions.py", line 505, in convert_chapters_to_audio
ebook2audiobookxtts-1  |     params['tts'] = XTTS(model_repo)
ebook2audiobookxtts-1  |   File "/usr/local/lib/python3.10/site-packages/TTS/api.py", line 96, in __init__
ebook2audiobookxtts-1  |     self.load_tts_model_by_name(model_name, vocoder_name, gpu=gpu)
ebook2audiobookxtts-1  |   File "/usr/local/lib/python3.10/site-packages/TTS/api.py", line 215, in load_tts_model_by_name
ebook2audiobookxtts-1  |     self.synthesizer = Synthesizer(
ebook2audiobookxtts-1  |   File "/usr/local/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 107, in __init__
ebook2audiobookxtts-1  |     self._load_fairseq_from_dir(model_dir, use_cuda)
ebook2audiobookxtts-1  |   File "/usr/local/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 153, in _load_fairseq_from_dir
ebook2audiobookxtts-1  |     self.tts_model.load_fairseq_checkpoint(self.tts_config, checkpoint_dir=model_dir, eval=True)
ebook2audiobookxtts-1  |   File "/usr/local/lib/python3.10/site-packages/TTS/tts/models/vits.py", line 1592, in load_fairseq_checkpoint
ebook2audiobookxtts-1  |     with open(config_file, "r", encoding="utf-8") as file:
ebook2audiobookxtts-1  | FileNotFoundError: [Errno 2] No such file or directory: '/home/user/app/models/tts/tts_models--hrv--fairseq--vits/config.json'
ebook2audiobookxtts-1  | Caught DependencyError: [Errno 2] No such file or directory: '/home/user/app/models/tts/tts_models--hrv--fairseq--vits/config.json'
ebook2audiobookxtts-1  | convert_ebook() Exception: [Errno 2] No such file or directory: '/home/user/app/models/tts/tts_models--hrv--fairseq--vits/config.json'
```

For some reason it is not able to load the Croatian model?

**Comment by ROBERT-MCDOWELL** [comment]
let me check....

**Comment by ak-42** [comment]
Ah, that sucks. There are so few audiobooks in Croatian, this would have been a game changer for my monolingual family. Thank you for putting this together, in any case, I might try it with French or English down the road.

**Comment by ROBERT-MCDOWELL** [comment]
ok I understand, I mistakenly add hrv croatian when ebook2audiobook was using spacy token package but didn' t catch that it was supporting language that neither xtts-v2 nor fairseq support it :-\.
if you find a good TTS engine supporting croatian I can try to implement it. it's a pitty that among the 1124 languages there is no croatian ....

**Comment by ROBERT-MCDOWELL** [comment]
We planned to add more TTS engine for the next release and we'll select one with Croatian and other missing languages.
I cannot say when it will be released. If you have more further info about it you can open a discussion so we will experiment it.

**Comment by ROBERT-MCDOWELL** [comment]
croation added! closing now.
