### ISSUE TITLE
XTTS can only generate text with a maximum of 400 tokens.

### ISSUE THREAD

**Issue by Code4SAFrankie** [DrewThomasson/ebook2audiobook#140]
Processing 9.85%: : 798/8093 Traceback (most recent call last):
  File "G:\ebook2audiobook-main\lib\functions.py", line 625, in convert_sentence_to_audio
    output = params['tts'].inference(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ebook2audiobook-main\python_env\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\ebook2audiobook-main\python_env\Lib\site-packages\TTS\tts\models\xtts.py", line 528, in inference
    text_tokens.shape[-1] < self.args.gpt_max_text_tokens
AssertionError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
Caught DependencyError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
Processing 9.85%: : 798/8093
Traceback (most recent call last):
  File "G:\ebook2audiobook-main\lib\functions.py", line 625, in convert_sentence_to_audio
    output = params['tts'].inference(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ebook2audiobook-main\python_env\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\ebook2audiobook-main\python_env\Lib\site-packages\TTS\tts\models\xtts.py", line 528, in inference
    text_tokens.shape[-1] < self.args.gpt_max_text_tokens
AssertionError:  ❗ XTTS can only generate text with a maximum of 400 tokens.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\ebook2audiobook-main\lib\functions.py", line 584, in convert_chapters_to_audio
    if convert_sentence_to_audio(params, session):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ebook2audiobook-main\lib\functions.py", line 657, in convert_sentence_to_audio
    raise DependencyError(e)
lib.functions.DependencyError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
Caught DependencyError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
convert_ebook() Exception:  ❗ XTTS can only generate text with a maximum of 400 tokens.

**Comment by ROBERT-MCDOWELL** [comment]
there is a bug on how sentences are splitted for now. next git update will solve your issue.

**Comment by Code4SAFrankie** [comment]
English

**Comment by ROBERT-MCDOWELL** [comment]
could yo provide which part of the text generates the error? I want to be sure my patch is fixing it.

**Comment by Code4SAFrankie** [comment]
How would I know that?

**Comment by DrewThomasson** [comment]
Just send a full log of the terminal as a txt file dude...

**Comment by Code4SAFrankie** [comment]
[tts.log](https://github.com/user-attachments/files/18281899/tts.log)
This is the log

**Comment by Code4SAFrankie** [comment]
![tts](https://github.com/user-attachments/assets/5bb21573-04ee-46c3-9582-5a3e1a948114)
This is an image of the page where it crashed.

**Comment by ROBERT-MCDOWELL** [comment]
well, do you really think the A.I. speaker is going to say  the example code, and a technical table without issue?

**Comment by majormer** [comment]
For what it is worth, I am using an RTX 4090 with 24GB of VRAM. Would it be possible to modify the value so I can do bigger than 400 tokens, or is it a function of how the voice stuff is generated?

**Comment by majormer** [comment]
And I did just end up editing the ebook to modify that line to truncate the number, since it didn't add anything to the story... but wanted to provide the context of my issue. I wish there was a resume...

**Comment by ROBERT-MCDOWELL** [comment]
it's a TTS limitation. all A.I. today cannot or don't want more than a certain number of token for accuracy. maybe in 5 years we will swallow to it the entire book once... but it's not the case today.
this is normally fixed next update, I don't know when as I need to fix other things.

**Comment by majormer** [comment]
An interesting consideration is to add the ability to optionally scan the file before committing to the conversion. Check tokens per the settings selected and validate that everything is compliant.

**Comment by majormer** [comment]
I think text splitting might be the only factor I can think of for my above suggestion.

**Comment by ROBERT-MCDOWELL** [comment]
it's not as easy you think to split text when you have 1124 languages to manage....

**Comment by Digital-Yeti** [comment]
I also cannot convert my book because of this splitting error.
`
53;
 Other ways in which machinery affects the production of raw material will be mentioned in Volume 03;
*
*As it turned out, Volume 03 of Capital, when published, 
                               Sentence: contained nothing on this subject, 
Processing 58.34%: : 2769/4745 Sentence: although Chapters 40–44 (on the second form of differential rent) did deal with the related topic of the impact of extra amounts of capital directly invested in land;

54; 
                               Sentence: Export of cotton from India to Great Britain: 34,540,143 lb;
 in 1846; 204,141,168 lb;/4745 
 in 1860; 445,947,600 lb;
 in 1865;
 Export of wool from India to Great Britain: 4,570, 
                               Traceback (most recent call last):
  File "/home/user/app/lib/functions.py", line 583, in convert_sentence_to_audio
    output = params['tts'].inference(
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 528, in inference
    text_tokens.shape[-1] < self.args.gpt_max_text_tokens
AssertionError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
Caught DependencyError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
`

**Comment by majormer** [comment]
> it's not as easy you think to split text when you have 1124 languages to manage....

I think I understand. However, you have a current process for doing that, correct? My thought is that you do a dry-run of the current text split without the actual audio conversion just to see where the text-splits land, then check the tokens for them to make sure they are compliant. I'm not sure that it would require a rewrite of the text-splitting system. Just a thought, as it might save days of time and energy for users... especially those without GPUs or slower GPUs.

I guess this also depends on if you are using GenAI to actually come up with the text splits vs. an algorithm done purely on CPU. I suppose I could look at the code myself and see, but don't know that I have the time to come up with a solution and submit a pull request.

**Comment by ROBERT-MCDOWELL** [comment]
text splitting should be fixed in the next  update.

**Comment by ROBERT-MCDOWELL** [comment]
@majormer could you please provide your original text to make my last test for the fix of this issue?

**Comment by majormer** [comment]
> @majormer could you please provide your original text to make my last test for the fix of this issue?

It was posted above, but this is the original text that caused the crash:

=================================

It was so deep down it would be bad…to change it. But why? Why—did it look like something had been changed?

Focus. What did you multiply Erin’s achievements by? Oh, it was simple if you looked. Though it was so long and precise; no wonder it was always skipped. You had to round it because it was like counting…multiply Erin’s deeds by…

3.1415926535 8979323846 2643383279 5028841971 6939937510 5820974944 5923078164 0628620899 8628034825 3421170679 8214808651 3282306647 0938446095 5058223172 5359408128 4811174502 8410270193 8521105559 6446229489 5493038196 4428810975 6659334461 2847564823 3786783165 2712019091 4564856692 3460348610 4543266482 1339360726 0249141273 7245870066 0631558817 4881520920 9628292540 9171536436 7892590360 0113305305 4882046652 1384146951 9415116094 3305727036 5759591953 0921861173 8193261179 3105118548 0744623799 6274956735 1885752724 8912279381 8301194912 9833673362 4406566430 8602139494 6395224737 1907021798 6094370277 0539217176 2931767523 8467481846 7669405132 0005681271 4526356082 7785771342 7577896091 7363717872 1468440901 2249534301 4654958537 1050792279 6892589235 4201995611 2129021960 8640344181 5981362977 4771309960 5187072113 4999999837 2978049951 0597317328 1609631859 5024459455 3469083026 4252230825 3344685035 2619311881 7101000313 7838752886 5875332083 8142061717 7669147303 5982534904 2875546873 1159562863 8823537875 9375195778 1857780532 1712268066 1300192787 6611195909…

It was counting infinity each time. But just a symbol. What was it? Oh yes. Multiply by π. What the—

<Red|Who wrote that?|Red>

===================================

**Comment by ROBERT-MCDOWELL** [comment]
btw is special mathematic chars like "π" were ok or not?

**Comment by majormer** [comment]
Pi worked fine. It was the long strong of numbers

**Comment by ROBERT-MCDOWELL** [comment]
I mean you don't know if the voice pronounced it well as it crashed......

**Comment by majormer** [comment]
Incorrect. I changed the text of the number and re-ran the entire book. It
completed successfully, including the pi character.

**Comment by ROBERT-MCDOWELL** [comment]
ok so do you confirm the voice is pronouncing well special chars like Pi ?

**Comment by majormer** [comment]
Well, I just went back to verify, and there is a gap. I only spot-checked the generated file.

This is the original text:

![image](https://github.com/user-attachments/assets/4e16cc1a-1918-4bd8-afa9-8aa1a33aae20)

And it actually SAID:

Three fourteen fifteen (fade-out)
*GAP*
getting mad about the unfairness...


Although in finding this sample, I found other gaps in the speech as well. When I processed the e-book, I unchecked the "Enable text splitting" option, so not sure if that lead to gaps or not. I'm now going through the sentences that are still in the temp directory to see if it rendered, but it might take a bit as there are 41038 un-labeled wav files to pick at, and I haven't read the book to know the general location of a given sentence. I'll follow up on that soon, to see if it processed the voice at the sentence level.

**Comment by majormer** [comment]
I guess I'm saying that it didn't crash, but it also didn't bother with even the entire shortened number.

**Comment by ROBERT-MCDOWELL** [comment]
ok despite of your issue which is already solved on the next update.
I'm talking about special mathematics characters like  "π" . Is the voice pronounce it or not?

**Comment by ROBERT-MCDOWELL** [comment]
create a simple text with a sentence with  "π"  in it. and tell me if  "π" is said or not... I need test from others than only my tests.

**Comment by majormer** [comment]
Well, I did find the .wav file, or rather not:

<img width="751" alt="image" src="https://github.com/user-attachments/assets/2054901f-cf2c-4330-b743-323a19e68940" />

There should be a wav file with "π" in it, but it is missing. All the text in bold was skipped between those two files:

3.1415**926535…

It was counting infinity each time. But just a symbol. What was it? Oh yes. Multiply by π. What the—

<Red|Who wrote that?|Red>

 

——

 

If you were—**getting mad about the unfairness of the world, of iniquitous sides, 



I'll work on getting a file created with pi in it and follow up. Gimme a few.

**Comment by majormer** [comment]
It does not say the pi character. I used the sentence "Wideacre Hall faces due π and the π shines all day on the yellow stone until it is warm and powdery to the touch"

It skipped the first π entirely, and the second one almost sounds like it was pronounced like you would say the long U sound.

I would attach the .wav file here, but it won't let me.

**Comment by majormer** [comment]
[3.zip](https://github.com/user-attachments/files/18350277/3.zip)

**Comment by majormer** [comment]
There. I attached the generated .wav file with the sentence above.

**Comment by BigRusBoss** [comment]
Book:

[zigel-ufo-ussr.zip](https://github.com/user-attachments/files/18482514/zigel-ufo-ussr.zip)

Error:
```
lib.functions.DependencyError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
Caught DependencyError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
convert_ebook() Exception:  ❗ XTTS can only generate text with a maximum of 400 tokens.
```
Full log:
```
Available Processor Unit: cuda
C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\ebooklib\epub.py:1395: UserWarning: In the future version we will turn default option ignore_ncx to True.
  warnings.warn('In the future version we will turn default option ignore_ncx to True.')
C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\ebooklib\epub.py:1423: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/xmlns:rootfile[@media-type]'
  for root_file in tree.findall('//xmlns:rootfile[@media-type]', namespaces={'xmlns': NAMESPACES['CONTAINERNS']}):
1% Конвертирую входной файл в HTML...
InputFormatPlugin: EPUB Input running
on C:\Tool\ebook2audiobook-2.0\tmp\ebook-cdbd6b54-75d3-4312-bdc2-b9c06021a5ed\zigel-ufo-ussr.epub
Parsing all content...
34% Выполняются изменения в электронной книге…
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Creating EPUB Output...
67% Запускается плагин EPUB Output
Splitting markup on page breaks and flow limits, if any...
        Looking for large trees in index_split_002.xhtml...
        No large trees found
        Looking for large trees in index_split_005.xhtml...
        No large trees found
        Looking for large trees in index_split_007.xhtml...
        No large trees found
        Looking for large trees in index_split_008.xhtml...
        No large trees found
        Looking for large trees in index_split_009.xhtml...
        No large trees found
        Looking for large trees in index_split_010.xhtml...
        No large trees found
        Looking for large trees in index_split_000.xhtml...
        No large trees found
        Looking for large trees in index_split_001.xhtml...
        No large trees found
        Looking for large trees in index_split_004.xhtml...
        No large trees found
        Looking for large trees in index_split_003.xhtml...
        No large trees found
        Looking for large trees in index_split_006.xhtml...
        No large trees found
Generating default cover
EPUB output written to C:\Tool\ebook2audiobook-2.0\tmp\ebook-cdbd6b54-75d3-4312-bdc2-b9c06021a5ed\__zigel-ufo-ussr.epub
Выходные данные сохранены в   C:\Tool\ebook2audiobook-2.0\tmp\ebook-cdbd6b54-75d3-4312-bdc2-b9c06021a5ed\__zigel-ufo-ussr.epub
Loading TTS xtts model from tts_models/multilingual/multi-dataset/xtts_v2...
Resuming from chapter 2
Resuming from sentence 166
convert_chapters_to_audio 0.00%: 166/2083
Chapter 2 containing 94 sentences...

End of Chapter 2

Chapter 3 containing 322 sentences...
Processing 7.97%: : 167/2083              Sentence: углубления от "посадочных опор" и следы ног;
 Сообщалось о повреждениях, обнаруженных рядом с предполагаемым путем движения НЛО;
 Имеется большое количество сообщений,
Processing 8.02%: : 168/2083 Sentence: в которых говорится о том, что на местах посадок исчезала биологическая активность, в нескольких случаях животные долго избегали этого места;
Так как земные эффекты, в отличие от самих НЛО,
Processing 8.07%: : 169/2083 Sentence: никуда не улетают, оставив только возбуждающее воспоминание у наблюдателя, а остаются на месте, они могут быть измерены, сфотографированы и изучены;
 Я считаю,
Processing 8.11%: : 170/2083 Sentence: что физические следы представляют наиболее важную часть проблемы НЛО;
Прежде чем представить три блестящих случая оставления следов,
Processing 8.16%: : 171/2083 Sentence: я хочу показать общие статистические данные;
Распределение по годам: 1490 — 1, 1687 — 1, 1790 — 1, 1872 — 1, 1880 — 1, 1897 — 4, 1908 — 1, 1909 — 2, 1919 — 1, 1923 — 1, 1941 — 1, 1943 — 1,
Processing 8.16%: : 171/2083 Traceback (most recent call last):
  File "C:\Tool\ebook2audiobook-2.0\lib\functions.py", line 596, in convert_sentence_to_audio
    params['tts'].tts_to_file(
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\TTS\api.py", line 377, in tts_to_file
    wav = self.tts(
          ^^^^^^^^^
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\TTS\api.py", line 323, in tts
    wav = self.synthesizer.tts(
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\TTS\utils\synthesizer.py", line 422, in tts
    outputs = self.tts_model.synthesize(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\TTS\tts\models\xtts.py", line 406, in synthesize
    return self.full_inference(text, speaker_wav, language, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\TTS\tts\models\xtts.py", line 475, in full_inference
    return self.inference(
           ^^^^^^^^^^^^^^^
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\TTS\tts\models\xtts.py", line 524, in inference
    text_tokens.shape[-1] < self.args.gpt_max_text_tokens
AssertionError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
Caught DependencyError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
Processing 8.16%: : 171/2083
Traceback (most recent call last):
  File "C:\Tool\ebook2audiobook-2.0\lib\functions.py", line 596, in convert_sentence_to_audio
    params['tts'].tts_to_file(
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\TTS\api.py", line 377, in tts_to_file
    wav = self.tts(
          ^^^^^^^^^
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\TTS\api.py", line 323, in tts
    wav = self.synthesizer.tts(
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\TTS\utils\synthesizer.py", line 422, in tts
    outputs = self.tts_model.synthesize(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\TTS\tts\models\xtts.py", line 406, in synthesize
    return self.full_inference(text, speaker_wav, language, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\TTS\tts\models\xtts.py", line 475, in full_inference
    return self.inference(
           ^^^^^^^^^^^^^^^
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tool\ebook2audiobook-2.0\python_env\Lib\site-packages\TTS\tts\models\xtts.py", line 524, in inference
    text_tokens.shape[-1] < self.args.gpt_max_text_tokens
AssertionError:  ❗ XTTS can only generate text with a maximum of 400 tokens.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Tool\ebook2audiobook-2.0\lib\functions.py", line 542, in convert_chapters_to_audio
    if convert_sentence_to_audio(params, session):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tool\ebook2audiobook-2.0\lib\functions.py", line 615, in convert_sentence_to_audio
    raise DependencyError(e)
lib.functions.DependencyError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
Caught DependencyError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
convert_ebook() Exception:  ❗ XTTS can only generate text with a maximum of 400 tokens.
```
Judging by the log, I understand that the error occurred in this section of the text:
```
Processing 8.16%: : 171/2083 Sentence: я хочу показать общие статистические данные;
Распределение по годам: 1490 — 1, 1687 — 1, 1790 — 1, 1872 — 1, 1880 — 1, 1897 — 4, 1908 — 1, 1909 — 2, 1919 — 1, 1923 — 1, 1941 — 1, 1943 — 1,
Processing 8.16%: : 171/2083 Traceback (most recent call last):
  File "C:\Tool\ebook2audiobook-2.0\lib\functions.py", line 596, in convert_sentence_to_audio
    params['tts'].tts_to_file(
```

**Comment by ROBERT-MCDOWELL** [comment]
outbound tokens fixed in last git.

**Comment by ArmaanSethi** [comment]
I'm getting the same error using English with Colab and gradio.

Here is a copy of my colab with the error logs (In the "Show hidden output"):
https://colab.research.google.com/drive/1IFKaAQRDCcHnIBozEjcK5AG6XB1R0sfD?usp=sharing

**Comment by ROBERT-MCDOWELL** [comment]
> I'm getting the same error using English with Colab and gradio.
> 
> Here is a copy of my colab with the error logs (In the "Show hidden output"): https://colab.research.google.com/drive/1IFKaAQRDCcHnIBozEjcK5AG6XB1R0sfD?usp=sharing

share the text pls

**Comment by ROBERT-MCDOWELL** [comment]
fixed on the next update.

**Comment by mkarikom** [comment]
@ROBERT-MCDOWELL I got the same error on an actual English sentence (please see below) with a pull from main branch today.
Can you please confirm which branch fixes this?

```
******* NOTE: YOU CAN SAFELY IGNORE "Character xx not found in the vocabulary." *******
Loading TTS tts_models/multilingual/multi-dataset/xtts_v2 model, it takes a while, please be patient...
Resuming from block 1
Resuming from sentence 260
convertsion 0.00%:  16% 260/1618 [00:00<?, ?step/s]Block 1 containing 115 sentences...
End of Block 1
**Recovering missing file block 1
ffmpeg version 5.1.6-0+deb12u1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, concat, from '/app/tmp/ebook-ef7b41e6-ad3f-4712-b6fc-692296e905a6/fae5cb2d83b2b832f68e21685668a5f9/chapters/sentences/sentences.txt':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Audio: flac, 24000 Hz, mono, s16
Stream mapping:
  Stream #0:0 -> #0:0 (flac (native) -> flac (native))
Press [q] to stop, [?] for help
Output #0, flac, to '/app/tmp/ebook-ef7b41e6-ad3f-4712-b6fc-692296e905a6/fae5cb2d83b2b832f68e21685668a5f9/chapters/chapter_1.flac':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Audio: flac, 24000 Hz, mono, s16, 128 kb/s
    Metadata:
      encoder         : Lavc59.37.100 flac
size=      11kB time=00:00:00.09 bitrate= 933.3kbits/s speed= 468x    
size=   20224kB time=00:12:48.28 bitrate= 215.6kbits/s speed=1.54e+03x    
size=   38548kB time=00:23:57.93 bitrate= 219.6kbits/s speed=1.58e+03x    
video:0kB audio:38540kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.021001%
********* Combined block audio file saved to /app/tmp/ebook-ef7b41e6-ad3f-4712-b6fc-692296e905a6/fae5cb2d83b2b832f68e21685668a5f9/chapters/chapter_1.flac
Combining block 1 to audio, sentence 0 to 114
Block 2 containing 169 sentences...
**Recovering missing file sentence 115
convertsion 0.00%:  16% 261/1618 [00:01<23:55,  1.06s/step]**Recovering missing file sentence 260
Converting 16.07%:  16% 261/1618 [00:13<23:55,  1.06s/step]
Sentence: We are left with these fugitive instants of apprehension , in both senses of that word , which is one reason why poetry , which is designed not simply to arrest these instants but to integrate them into life , can be such a powerful aid to faith .
Converting 16.07%:  16% 262/1618 [00:13<2:59:01,  7.92s/step]The text length exceeds the character limit of 250 for language 'en', this might cause truncated audio.
Converting 16.07%:  16% 262/1618 [00:13<2:35:51,  6.90s/step]
 ❗ XTTS can only generate text with a maximum of 400 tokens.
Traceback (most recent call last):
  File "/app/lib/classes/tts_manager.py", line 304, in convert_sentence_to_audio
    audio_data = self.params['tts'].tts(
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/TTS/api.py", line 323, in tts
    wav = self.synthesizer.tts(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/TTS/utils/synthesizer.py", line 422, in tts
    outputs = self.tts_model.synthesize(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/TTS/tts/models/xtts.py", line 396, in synthesize
    return self.inference(text, language, gpt_cond_latent, speaker_embedding, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/TTS/tts/models/xtts.py", line 522, in inference
    assert text_tokens.shape[-1] < self.args.gpt_max_text_tokens, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError:  ❗ XTTS can only generate text with a maximum of 400 tokens.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/functions.py", line 789, in convert_chapters_to_audio
    if tts_manager.convert_sentence_to_audio():
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/classes/tts_manager.py", line 470, in convert_sentence_to_audio
    raise ValueError(e)
ValueError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
Caught DependencyError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
convert_chapters_to_audio() failed!

```

**Comment by ROBERT-MCDOWELL** [comment]
@mkarikom 
as I said above it's already fixed for the next update coming soon. please be patient.

**Comment by Leon-Sander** [comment]
Also just got the error, hope this will be fixed soon

**Comment by DrewThomasson** [comment]
Don't worry

The `v25` branch should be pushed soon

**Comment by DrewThomasson** [comment]
What I'm trying to say is that if you really want it early you can switch to the `v25` branch...

**Comment by Leon-Sander** [comment]
Tried with docker compose on the v25 branch but it pulls the latest image, is there a v25 image?

**Comment by DrewThomasson** [comment]
Replace this line in the docker-compose

`image: docker.io/athomasson2/ebook2audiobook:latest`

With this line

```
build:
  context: .
  dockerfile: Dockerfile
```

Or just ask chatgpt how to modify the docker compose to build from the `Dockerfile` in the local directory of the Docker-compose file

**Comment by Leon-Sander** [comment]
It also didnt work and runs in v25.3.21 as well 
![Image](https://github.com/user-attachments/assets/f2b26554-3276-4a2e-b3ad-e68f9f71f405)

**Comment by ROBERT-MCDOWELL** [comment]
fixed on last git and v25.3.21

**Comment by Leon-Sander** [comment]
Yes @ROBERT-MCDOWELL it makes sense that v25.0.0 is not the fix, but I thought it might be an earlier version without the error in the first place, because I guess at some point the repository was working without throwing this specific Error.

Should'nt it be best to test in docker mode where everything is set up like you defined it without any configurations or set ups from my side interfering?

**Comment by ROBERT-MCDOWELL** [comment]
it's one one of the issue I worked the most, and the last git has been tested on many languages to avoid it, and passed.
the functions managing the tokens splitting are completely different from the 25.0.0 which was working on a certain point and not all languages. The docker must logically have the same code than the native that's why I asked to you to test on the native mode to be sure there is no issue with the docker.

**Comment by DrewThomasson** [comment]
Yeah the docker images take time to update
