### ISSUE TITLE
Fails on >24hr audiobooks & Reader Jumps Around

### ISSUE THREAD

**Issue by kkrausse** [DrewThomasson/ebook2audiobook#37]
Seems like the failure at >24hr books is because final wav file gets too big.

Another (somewhat) related issue is that ebook reader randomly pauses and like jump backwards to random places.

Have you considered using [m4b-tool](https://github.com/sandreas/m4b-tool) instead of combining wav files & making the metadata yourself? 

or maybe something with my files messes with the formatting.

edit: willing to work on this myself, but want to know if anyone has ideas first

**Comment by DrewThomasson** [comment]
## hm, Ill look into this 

but in the meantime I suppose you could try removing the activation of the `create_m4b_from_chapters()` function?

Then you should just be left with a bunch of chapter wav files located in the `Chapter_wav_files` dir?


Unless of course your issue comes before the creation of the final giant audiobook file

**Comment by ROBERT-MCDOWELL** [comment]
the best is standardize the audio file with a max time, for ex 2 hours, and a consistent naming convention
i.e: chapter-1.1, chapter-1.2 etc...
to split with ffmpeg something like 
ffmpeg -i long_audio.wav -f segment -segment_time 7200 chapter%03d.m4b

**Comment by kkrausse** [comment]
👍🏻 yeah for now I went the route of just commenting out create_m4b_from_chapters() and use [m4b-tool](https://github.com/sandreas/m4b-tool) to convert those which works great.

**Comment by ROBERT-MCDOWELL** [comment]
@kkrausse v2.0 is out now, but I'm still working on it. If you have already some code for a PR don't hesitate to share it.

**Comment by majormer** [comment]
I might have hit something like this.

<img width="650" alt="image" src="https://github.com/user-attachments/assets/cd11612b-d245-45ef-a5a0-4c5e9dc77364" />

28.4 GB of WAV files were generated for my audiobook. I need to get them combined. I'll look at using m4b-tool to merge them, I suppose, since the conversion took 2 days, but let me know if you need more info:

`Processing 100.00%: : 41039/41039
End of Chapter 41
Combined audio saved to W:\Personal\Repos\ebook2audiobook\tmp\ebook-8fdd5c5b-213b-4214-9e01-0b1c9c69c1c2\chapters_0587d54db0b22fe48ce814b608a119ac\chapter_41.wav
Combining chapter 41 to audio, sentence 39986 to 41038
Processing 100.00%: : 41039/41039
Traceback (most recent call last):
  File "W:\Personal\Repos\ebook2audiobook\lib\functions.py", line 709, in assemble_audio
    combined_audio.export(assembled_audio, format=audioproc_format)
  File "W:\Personal\Repos\ebook2audiobook\python_env\Lib\site-packages\pydub\audio_segment.py", line 895, in export
    wave_data.writeframesraw(pcm_for_wav)
  File "W:\Personal\Repos\ebook2audiobook\python_env\Lib\wave.py", line 565, in writeframesraw
    self._ensure_header_written(len(data))
  File "W:\Personal\Repos\ebook2audiobook\python_env\Lib\wave.py", line 606, in _ensure_header_written
    self._write_header(datasize)
  File "W:\Personal\Repos\ebook2audiobook\python_env\Lib\wave.py", line 618, in _write_header
    self._file.write(struct.pack('<L4s4sLHHLLHH4s',
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: 'L' format requires 0 <= number <= 4294967295
Caught DependencyError: 'L' format requires 0 <= number <= 4294967295
Traceback (most recent call last):
  File "W:\Personal\Repos\ebook2audiobook\lib\functions.py", line 709, in assemble_audio
    combined_audio.export(assembled_audio, format=audioproc_format)
  File "W:\Personal\Repos\ebook2audiobook\python_env\Lib\site-packages\pydub\audio_segment.py", line 895, in export
    wave_data.writeframesraw(pcm_for_wav)
  File "W:\Personal\Repos\ebook2audiobook\python_env\Lib\wave.py", line 565, in writeframesraw
    self._ensure_header_written(len(data))
  File "W:\Personal\Repos\ebook2audiobook\python_env\Lib\wave.py", line 606, in _ensure_header_written
    self._write_header(datasize)
  File "W:\Personal\Repos\ebook2audiobook\python_env\Lib\wave.py", line 618, in _write_header
    self._file.write(struct.pack('<L4s4sLHHLLHH4s',
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: 'L' format requires 0 <= number <= 4294967295

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "W:\Personal\Repos\ebook2audiobook\lib\functions.py", line 837, in combine_audio_chapters
    if assemble_audio():
       ^^^^^^^^^^^^^^^^
  File "W:\Personal\Repos\ebook2audiobook\lib\functions.py", line 713, in assemble_audio
    raise DependencyError(e)
lib.functions.DependencyError: 'L' format requires 0 <= number <= 4294967295
Caught DependencyError: 'L' format requires 0 <= number <= 4294967295
convert_ebook() Exception: 'L' format requires 0 <= number <= 4294967295`

**Comment by ROBERT-MCDOWELL** [comment]
it's a wav 32bit limited size. we need to add a function assembling the chunks once it reaches the limit which is 4GB.

**Comment by Mr-Jiggledaddy** [comment]
I changed the intermediate file type for the chapters to .mp3 @128kb/s in functions.py and haven't had any failures yet on the same files that previously failed due to the .wav file size limit.  Biggest so far is >20h long.  No clue if this could have other ramifications, but it's something that's worked for me so far.

**Comment by ROBERT-MCDOWELL** [comment]
well, you tried it before any one of us... good to know! :)

**Comment by ROBERT-MCDOWELL** [comment]
@majormer which function you changed to mp3?

**Comment by majormer** [comment]
Was not me, but interested in the answer!

**Comment by Mr-Jiggledaddy** [comment]
I changed combine_audio_sentences (line 681):   combined_audio.export(chapter_audio_file, format="mp3", bitrate="128k")

[functions.txt](https://github.com/user-attachments/files/18458355/functions.txt)

Here's the file converted to .txt so it'll let me upload.

I did have to change several other places where it checks for the file format (lines 555, 575, 833, 835), line 706 and 756 to from_mp3 instead of from_wav, and line 709 to format=mp3.  I'm pretty sure that's everything I changed, but I did still have a failure on a 36h audiobook.  

Pydub has a PR open to implement the following change to audio_segment.py to allow >4gb file sizes, and that new version of audio_segment did work even on the 36h book.

https://github.com/jiaaro/pydub/blob/4eb5818cff1fe65c1cbef40166c36c47df843287/pydub/audio_segment.py

Would probably be more efficient to just replace the use of pydub for chapters and directly combine the chapters using ffmpeg, but I'm not that skilled and my 2 young kids demand the time I'd use to do it for now.  

Really awesome project though, hope it can become everything you guys want it to be, it's already getting some really good use for me.

**Comment by ROBERT-MCDOWELL** [comment]
yes, it's absolutely what I'm started to do. switch pydub to ffmpeg libraries as it support RF64 wav and so on.
the issue with mp3 is you cannot concatenate mp3 files without to decode an reencode which is a huge loophole for resources and time conversion. > 4GB is the 32bits limitation which almost all audio files are limited to with some exceptions. for example FLAC, which I selected to be the next default audio processing as the compression and quality is remarkable and it can be concatenated without decode/reencode, and the size is even smaller than a good mp3 quality.

**Comment by Mr-Jiggledaddy** [comment]
Well, the 36h book I did with the previous attempt didn't actually work (output file showed 36h length, but only had 24h worth of actual audio).  Apparently the concatenation didn't quite work as intended.

Got bored late night over the weekend and took your suggestion to use flac, changed all the previous references to mp3 to flac, and rewrote the assemble_audio function for in combine_audio_chapters to directly utilize ffmpeg on the flac files.  

Just finished my first long book (34h) with the rewritten function and everything checks out.  Successfully combined 5.8gb of flac files into a 1.8gb m4b with no errors, and was much faster than the mp3 processing.  Only length limitation at this point would be if you had a single chapter over 4gb.  If I get bored again I may do the same thing with the combine_audio_sentences function to get rid of that limitation too.

Here's the rewritten portion of combine_audio_chapters if it helps anything.

    def assemble_audio():
        try:
            # Get a list of files in the directory
            chapterfiles = [f for f in os.listdir(session['chapters_dir']) if f.endswith('.flac')]

            if not chapterfiles:
                print("No files found in the directory.")
                return

            # Create a temporary text file with the list of files to concatenate
            temp_list_file = "temp_list.txt"
            with open(temp_list_file, "w") as f:
                for chapterfile in sorted(chapterfiles,key=lambda x: int(re.search(r'\d+', x).group())):
                    f.write(f"file '{os.path.join(session['chapters_dir'], chapterfile)}'\n")

            # Use ffmpeg to concatenate the files
            ffmpeg_command = [
                "ffmpeg",
                "-f", "concat",
                "-safe", "0",
                "-i", temp_list_file,
                "-c:a", "flac",
                assembled_audio
            ]
            subprocess.run(ffmpeg_command)

            # Delete the temporary list file
            os.remove(temp_list_file)

            print(f'Combined audio saved to {assembled_audio}')
            return True
        except Exception as e:
            raise DependencyError(e)

**Comment by ROBERT-MCDOWELL** [comment]
coming update the user will have choice to use more than 12 output formats.
also if the audiobook exceed 12hours it will stay in chapter files inside a folder.
so you don't won't need to repatch your repo with your function with ffmpeg.

**Comment by ROBERT-MCDOWELL** [comment]
@Mr-Jiggledaddy once the update is release I invite you to test it with the same ebook that fails before you change the function and tell me if it works. I'm sure at 99% it will work, but the 1% to fail is still possible too...

**Comment by ROBERT-MCDOWELL** [comment]
default format process is .flac now, should fix it. the process format can be modified in conf.py

**Comment by MachineGalaxy** [comment]
I'm still having this issue. On the latest version.

```
Traceback (most recent call last):
  File "/home/user/app/lib/functions.py", line 784, in assemble_audio
    combined_audio.export(combined_chapters_file, format=default_audio_proc_format)
  File "/home/user/.local/lib/python3.12/site-packages/pydub/audio_segment.py", line 895, in export
    wave_data.writeframesraw(pcm_for_wav)
  File "/usr/local/lib/python3.12/wave.py", line 565, in writeframesraw
    self._ensure_header_written(len(data))
  File "/usr/local/lib/python3.12/wave.py", line 606, in _ensure_header_written
    self._write_header(datasize)
  File "/usr/local/lib/python3.12/wave.py", line 618, in _write_header
    self._file.write(struct.pack('<L4s4sLHHLLHH4s',
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: 'L' format requires 0 <= number <= 4294967295
Exception ignored in: <function Wave_write.__del__ at 0x14b8188cf2e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/wave.py", line 465, in __del__
    self.close()
  File "/usr/local/lib/python3.12/wave.py", line 583, in close
    self._ensure_header_written(0)
  File "/usr/local/lib/python3.12/wave.py", line 606, in _ensure_header_written
    self._write_header(datasize)
  File "/usr/local/lib/python3.12/wave.py", line 618, in _write_header
    self._file.write(struct.pack('<L4s4sLHHLLHH4s',
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: 'L' format requires 0 <= number <= 4294967295
```

**Comment by ROBERT-MCDOWELL** [comment]
ok thanks for your report. I'm going to fix it today

**Comment by MachineGalaxy** [comment]
Awesome, Thank you.
Let me know if you need any extra info or need testing done. Happy to help where I can

**Comment by MachineGalaxy** [comment]
Total chapters: 62
total sentences: 14497

Yes, default_audio_proc_format exists and is set to flac: `default_audio_proc_format = 'flac'`

**Comment by ROBERT-MCDOWELL** [comment]
thanks I have all what I need.

**Comment by ROBERT-MCDOWELL** [comment]
should be fixed. do a git pull and test again thanks

**Comment by MachineGalaxy** [comment]
Trying to build from the repo, in both docker (Linux server) and windows im getting this error
```
ebook2audiobook-main\lib\functions.py", line 702, in convert_chapters_to_audio
    if sentence_number in missing_sentences or sentence_number > resume_sentence:
                          ^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'missing_sentences' where it is not associated with a value
Caught DependencyError: cannot access local variable 'missing_sentences' where it is not associated with a value
convert_chapters_to_audio() failed!
```

**Comment by ROBERT-MCDOWELL** [comment]
Sorry I made a typo, it's fixed now you can try again it should work

**Comment by MachineGalaxy** [comment]
Trying to build the docker container gives me this error

```
38.31 Loading TTS tts_models/multilingual/multi-dataset/xtts_v2 model, it takes a while, please be patient...
100%|██████████| 1.87G/1.87G [06:35<00:00, 4.73MiB/s]
100%|██████████| 4.37k/4.37k [00:00<00:00, 36.7kiB/s]
100%|██████████| 361k/361k [00:00<00:00, 1.23MiB/s]
100%|██████████| 32.0/32.0 [00:00<00:00, 201iB/s]
convertsion 0.00%: 0/1 7.75M [00:01<00:00, 7.08MiB/s]
445.9 Block 1 containing 1 sentences...
445.9 End of Block 1
445.9 No audio files found in the specified range.
445.9 combine_audio_sentences() failed!
445.9 convert_chapters_to_audio() failed!
445.9 *********** Session: 3c9e71ce-f8e0-4b61-a508-417b90cf739e **************
445.9 Store it in case of interruption, crash, reuse of custom model or custom voice,
445.9 you can resume the conversion with --session option
445.9 Conversion failed: convert_chapters_to_audio() failed!
445.9 *********** Session: 3c9e71ce-f8e0-4b61-a508-417b90cf739e **************
445.9 Store it in case of interruption, crash, reuse of custom model or custom voice,
445.9 you can resume the conversion with --session option
100%|██████████| 7.75M/7.75M [00:12<00:00, 618kiB/s]
------
Dockerfile:51
--------------------
  49 |     # Do a test run to make sure that the base models are pre-downloaded and baked into the image
  50 |     RUN echo "This is a test sentence." > test.txt
  51 | >>> RUN python app.py --headless --ebook test.txt --script_mode full_docker
  52 |     RUN rm test.txt
  53 |
--------------------
ERROR: failed to solve: process "/bin/sh -c python app.py --headless --ebook test.txt --script_mode full_docker" did not complete successfully: exit code: 1
```

and on Windows it gives me this error
```
Loading TTS tts_models/multilingual/multi-dataset/xtts_v2 model, it takes a while, please be patient...
100%|████████████████████████████████████████████████████████████████████████████| 1.87G/1.87G [05:09<00:00, 6.03MiB/s]
100%|████████████████████████████████████████████████████████████████████████████| 4.37k/4.37k [00:00<00:00, 29.4kiB/s]
100%|██████████████████████████████████████████████████████████████████████████████| 361k/361k [00:00<00:00, 1.21MiB/s]
100%|████████████████████████████████████████████████████████████████████████████████| 32.0/32.0 [00:00<00:00, 178iB/s]
 96%|██████████████████████Block 1 containing 1 sentences...█████████████████▋   | 7.42M/7.75M [00:01<00:00, 6.75MiB/s]
End of Block 100%: 0/14497
No audio files found in the specified range.
combine_audio_sentences() failed!
convertsion 0.00%: 0/14497
convert_chapters_to_audio() failed!
100%|████████████████████████████████████████████████████████████████████████████| 7.75M/7.75M [00:18<00:00, 6.75MiB/s]
```

**Comment by DrewThomasson** [comment]
> Trying to build the docker container gives me this error
> 
> ```
> 38.31 Loading TTS tts_models/multilingual/multi-dataset/xtts_v2 model, it takes a while, please be patient...
> 100%|██████████| 1.87G/1.87G [06:35<00:00, 4.73MiB/s]
> 100%|██████████| 4.37k/4.37k [00:00<00:00, 36.7kiB/s]
> 100%|██████████| 361k/361k [00:00<00:00, 1.23MiB/s]
> 100%|██████████| 32.0/32.0 [00:00<00:00, 201iB/s]
> convertsion 0.00%: 0/1 7.75M [00:01<00:00, 7.08MiB/s]
> 445.9 Block 1 containing 1 sentences...
> 445.9 End of Block 1
> 445.9 No audio files found in the specified range.
> 445.9 combine_audio_sentences() failed!
> 445.9 convert_chapters_to_audio() failed!
> 445.9 *********** Session: 3c9e71ce-f8e0-4b61-a508-417b90cf739e **************
> 445.9 Store it in case of interruption, crash, reuse of custom model or custom voice,
> 445.9 you can resume the conversion with --session option
> 445.9 Conversion failed: convert_chapters_to_audio() failed!
> 445.9 *********** Session: 3c9e71ce-f8e0-4b61-a508-417b90cf739e **************
> 445.9 Store it in case of interruption, crash, reuse of custom model or custom voice,
> 445.9 you can resume the conversion with --session option
> 100%|██████████| 7.75M/7.75M [00:12<00:00, 618kiB/s]
> ------
> Dockerfile:51
> --------------------
>   49 |     # Do a test run to make sure that the base models are pre-downloaded and baked into the image
>   50 |     RUN echo "This is a test sentence." > test.txt
>   51 | >>> RUN python app.py --headless --ebook test.txt --script_mode full_docker
>   52 |     RUN rm test.txt
>   53 |
> --------------------
> ERROR: failed to solve: process "/bin/sh -c python app.py --headless --ebook test.txt --script_mode full_docker" did not complete successfully: exit code: 1
> ```
> 
> and on Windows it gives me this error
> 
> ```
> Loading TTS tts_models/multilingual/multi-dataset/xtts_v2 model, it takes a while, please be patient...
> 100%|████████████████████████████████████████████████████████████████████████████| 1.87G/1.87G [05:09<00:00, 6.03MiB/s]
> 100%|████████████████████████████████████████████████████████████████████████████| 4.37k/4.37k [00:00<00:00, 29.4kiB/s]
> 100%|██████████████████████████████████████████████████████████████████████████████| 361k/361k [00:00<00:00, 1.21MiB/s]
> 100%|████████████████████████████████████████████████████████████████████████████████| 32.0/32.0 [00:00<00:00, 178iB/s]
>  96%|██████████████████████Block 1 containing 1 sentences...█████████████████▋   | 7.42M/7.75M [00:01<00:00, 6.75MiB/s]
> End of Block 100%: 0/14497
> No audio files found in the specified range.
> combine_audio_sentences() failed!
> convertsion 0.00%: 0/14497
> convert_chapters_to_audio() failed!
> 100%|████████████████████████████████████████████████████████████████████████████| 7.75M/7.75M [00:18<00:00, 6.75MiB/s]
> ```

This error is a duplicate of https://github.com/DrewThomasson/ebook2audiobook/issues/368

Please post there about this new error

Thanks
