### ISSUE TITLE
AssertionError:  ❗ XTTS can only generate text with a maximum of 400 tokens.

### ISSUE THREAD

**Issue by msameeh** [DrewThomasson/ebook2audiobook#56]
Just got the following error, seems to be hitting the limit in coqui TTS.

```
Chapter 50:  20%|████████████▌                                                  | 1/5 [10:51<43:25, 651.28s/it]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "Y:\dev\python\ebook2audiobook\app.py", line 956, in <lambda>
    lambda *args: convert_ebook_to_audio(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "Y:\dev\python\ebook2audiobook\app.py", line 801, in convert_ebook_to_audio
    convert_chapters_to_audio_standard_model(chapters_directory, output_audio_directory, temperature, length_penalty, repetition_penalty, top_k, top_p, speed, enable_text_splitting, target_voice, language)
  File "Y:\dev\python\ebook2audiobook\app.py", line 704, in convert_chapters_to_audio_standard_model
    tts.tts_to_file(
  File "C:\Users\user\anaconda3\Lib\site-packages\TTS\api.py", line 334, in tts_to_file
    wav = self.tts(
          ^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\TTS\api.py", line 276, in tts
    wav = self.synthesizer.tts(
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\TTS\utils\synthesizer.py", line 389, in tts
    outputs = self.tts_model.synthesize(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\TTS\tts\models\xtts.py", line 425, in synthesize
    return self.full_inference(text, speaker_wav, language, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\TTS\tts\models\xtts.py", line 494, in full_inference
    return self.inference(
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\TTS\tts\models\xtts.py", line 543, in inference
    text_tokens.shape[-1] < self.args.gpt_max_text_tokens
AssertionError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
```

**Comment by DrewThomasson** [comment]
### We have a fix for this being implemented in the next coming update

### In the mean time You could try setting 

`enable_text_splitting True`

It's also a checkbox option in the web gui as well

<img width="1003" alt="Screenshot 2024-11-19 at 10 33 02 PM" src="https://github.com/user-attachments/assets/a4d290d4-aa52-49e8-8127-ebc75c43a214">

## See if that fixes it for you in the meantime :)

**Comment by davpascoal** [comment]
Hello! tried the Text Splitting and doesn't work. Looking forward to the fix :)

**Comment by msameeh** [comment]
Bump! Does not fix with Text Splitting enabled. Same error as before.

**Comment by DrewThomasson** [comment]
Version 2.0 has just been released that should fix your issue!

if your issue persists you can reopen this issue! :)
